<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.2.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4a3cb98e-8f81-4cef-9f63-38b0c6a14246</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contoso.DailyBalance.API\Contoso.DailyBalance.API.csproj" />
    <ProjectReference Include="..\Contoso.DailyBalance.Worker\Contoso.DailyBalance.Worker.csproj" />
    <ProjectReference Include="..\Contoso.DatabaseMigrationService\Contoso.DatabaseMigrationService.csproj" />
    <ProjectReference Include="..\Contoso.Transactions.API\Contoso.Transactions.API.csproj" />
    <ProjectReference Include="..\Contoso.Transactions.Worker\Contoso.Transactions.Worker.csproj" />
    <ProjectReference Include="..\Contoso.Web\Contoso.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.2.0" />
    <PackageReference Include="Aspire.Hosting.Kafka" Version="9.2.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.2.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.2.0" />
	  <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
	  <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="9.0.0" />
  </ItemGroup>

</Project>
